import React from 'react';
import styles from './Styles/About.module.scss';
import { BsArrow90DegRight } from 'react-icons/bs';
import { IoIosArrowRoundForward } from 'react-icons/io';
import aditya from '../assets/aditya.jpg';
import react from '../assets/HoverIcons/react.svg';
import male from '../assets/male.jpg';

const About = () => {
	return (
		<div className={styles.main}>
			<div className={styles.heading}>
				<h2>ABOUT ME</h2>
				<div className={styles.smallInfo}>
					<p>Know more about me</p>
					<IoIosArrowRoundForward />
				</div>
			</div>
			<div className={styles.dataWrapper}>
				<img
					src={male}
					alt=''
				/>
				<p data-magnify='true'>
					A LEARNING DATA SCIENTIST HAVING SOME SKILLS
					IN THE PARTICULAR FIELD. ALONG WITH THAT, I
					HAVE INTEREST IN WEB DEVELOPMENT WITH A
					PASSION FOR CREATING VISUALLY STUNNING AND
					INTUITIVE WEBSITES. YOU CAN FIND ME TINKERING
					WITH NEW FRAMEWORKS AND TOOLS, OR
					COLLABORATING WITH FELLOW DEVELOPERS ON OPEN
					SOURCE PROJECTS . I AM EXCITED TO BRING MY
					SKILLS AND EXPERIENCE TO NEW CHALLENGES AND
					AM ALWAYS LOOKING FOR OPPORTUNITIES TO
					COLLABORATE AND CREATE AMAZING WEBSITES. A
					LEARNING DATA SCIENTIST HAVING SOME SKILLS IN
					THE PARTICULAR FIELD. ALONG WITH THAT, I HAVE
					INTEREST IN WEB DEVELOPMENT WITH A PASSION
					FOR CREATING VISUALLY STUNNING AND INTUITIVE
					WEBSITES. YOU CAN FIND ME TINKERING WITH NEW
					FRAMEWORKS AND TOOLS, OR COLLABORATING WITH
					FELLOW DEVELOPERS ON OPEN SOURCE PROJECTS . I
					AM EXCITED TO BRING MY SKILLS AND EXPERIENCE
					TO NEW CHALLENGES AND AM ALWAYS LOOKING FOR
					OPPORTUNITIES TO COLLABORATE AND CREATE
					AMAZING WEBSITES. A LEARNING DATA SCIENTIST
					HAVING SOME SKILLS IN THE PARTICULAR FIELD.
					ALONG WITH THAT, I HAVE INTEREST IN WEB
					DEVELOPMENT WITH A PASSION FOR CREATING
					VISUALLY STUNNING AND INTUITIVE WEBSITES. YOU
					CAN FIND ME TINKERING WITH NEW FRAMEWORKS AND
					TOOLS, OR COLLABORATING WITH FELLOW
					DEVELOPERS ON OPEN SOURCE PROJECTS . I AM
					EXCITED TO BRING MY SKILLS AND EXPERIENCE TO
					NEW CHALLENGES AND AM ALWAYS LOOKING FOR
					OPPORTUNITIES TO LEARN NEW OPPORTUNITIES TO
					LEARN NEW THINGS AND COLLABORATE AND CREATE
					OPPORTUNITIES TO LEARN NEW THINGS AND CREATE
					A NEW OPPORTUNITIES TO LEARN NEW THINGS AND
					CREATE A !
				</p>
			</div>
		</div>
	);
};

export default About;
